spring:
  application:
    name: SB08-Deokhugam-teamGwanwoong
  # ?? ??? ?? (?? ??? ? prod? ???? ?? ??)
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: prod

# Actuator ??
management:
  endpoints:
    web:
      exposure:
        # ??? ??? ????? ??
        include: health,info,metrics,loggers
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
